name: publish-both-registries

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ensure npm uses GitHub Packages for the package scope and has auth
          npm config set @jlu005807:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken ${NODE_AUTH_TOKEN}
          npm publish --registry=https://npm.pkg.github.com/

